apiVersion: v1
kind: Pod

metadata:
  name: demo-app-pod
  labels:
      app: demo-app
      type: front-end

spec:
  containers:
    - name: demo-app-container
      image: avpatel257/k8s-docker-demo-web
