apiVersion: v1
kind: Pod

metadata:
  name: demo-app-pod
  labels:
      app: demo-app
      type: front-end
      version: 1.0.0

spec:
  containers:
    - name: demo-app-container
      image: <YOUR-DOCKER-REPO>/<YOUR-DOCKER-IMAGE>
      ports:
          - containerPort: 8080
