apiVersion: v1
kind: ReplicationController
metadata:
  name: demo-app
spec:
  replicas: 2
  selector:
    app: demo-app
    version: 1.0.0
  template:
    metadata:
      name: demo-app
      labels:
        app: demo-app
        type: front-end
        version: 1.0.0

    spec:
      containers:
        - name: demo-app-container
          image: <YOUR-DOCKER-REPO>/<YOUR-DOCKER-IMAGE>
          ports:
            - containerPort: 8080
