apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
      version: 2.0.0
  template:
    metadata:
      labels:
        app: demo-app
        type: front-end
        version: 2.0.0
    spec:
      containers:
      - name: demo-app-container
        image: <YOUR-DOCKER-REPO>/<YOUR-DOCKER-IMAGE>:<IMAGE-VERSION-2>
        # resources:
        #   limits:
        #     memory: "512Mi"
        #     cpu: "1"
        ports:
        - containerPort: 8080

  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
