apiVersion: v1
kind: Service

metadata:
  name: demo-service

spec:
  type: NodePort
  ports:
    - targetPort: 8080
      port: 8080
      # valid nodePort range is 30000-32767. If you don't supply one, a random port will be picked and used as nodePort
      nodePort: 30609
  selector:
    app: demo-app
    type: front-end
    version: 1.0.0